name: Rust Build and Test with Cargo
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'outerspacedevs/Raider.rs'
    strategy:
      matrix:
        toolchain: [stable,beta,nightly]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Rust toolchain (${{ matrix.toolchain }})
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
        components: rustfmt, clippy
    - name: Cargo - Build
      run: cargo build --verbose
    - name: Cargo - Run tests
      run: cargo test --verbose
