name: Rust lint using clippy
on:
  push:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'outerspacedevs/Raider'
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up stable Rust environment
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Clippy Lint
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
